# Generated by Django 4.2.27 on 2025-12-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='lipanatransaction',
            name='callback_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lipanatransaction',
            name='stk_push_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lipanatransaction',
            name='stk_push_code',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='lipanatransaction',
            name='stk_push_message',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
