# Generated by Django 4.2.27 on 2025-12-15 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
